name: nerve_network_ninja
description: Network Ninja adapter for Nerve.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  nerve_core:
    path: ../nerve_core
  nerve_flutter:
    path: ../nerve_flutter
  network_ninja:
    git:
      url: https://github.com/YangLi-dev/network_ninja.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
